server:
  port: 8001
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bbzhanshi999/config-repo.git
          username: bbzhanshi999@163.com
          password: bbzhanshi321
          search-paths: demo-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
