server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:127.0.0.1}:${server.port:8761}/eureka
    fetch-registry: false
    register-with-eureka: false