server:
  port: 8083
spring:
  application:
    name: patient
  data:
    mongodb:
      database: his2
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

